repo_url : https://github.com/c01dkit/tech-blog
site_name: c01dkit's tech blog
site_author: c01dkit
site_url: https://tech.c01dkit.com
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
docs_dir: docs
copyright: '2023 Content provided by c01dkit'


nav:
  - 首页: index.md
  - linux服务器运维: linux-server.md
  - 编程语言:
    - C语言: c.md
    - Go: go.md
    - Python: python.md
    - 优雅编程: code-gracely.md
  - 程序逆向:
    - IDA基础: IDA.md
    - 逆向基础: reverse-basic.md
    - 逆向高阶: reverse-advanced.md
  - 学习笔记:
    - Git: git.md
    - Docker: docker.md
    - 根因分析: rca.md
    - pwn-college:
      - CSE 365 - spring 2023: pwn-college-cse365-spring2023.md
  - 科研生活: 
    - 科研心得: sci-thoughts.md
    - latex基础: latex.md
    - 词汇学习: word-learning.md
    - 文句摘录: picking-ups.md
    - 情景模板: sentence-templates.md
    - 四大调查: investigations.md
    - 有趣文章: interesting-articles.md
  - 其他杂项:
    - 模糊测试: fuzzing.md
    - 服务器端口复用: porting.md
    - ChatGPT: try-chatgpt.md
    - 环境配置: envs.md
    

    
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
